name: Vulnerability Scan

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull mlsecproject/gglsbl-rest

      - uses: homoluctus/gitrivy@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: mlsecproject/gglsbl-rest
